//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod crate_tracks;
pub mod crates;
pub mod cues;
pub mod directories;
pub mod itunes_library;
pub mod itunes_playlist_tracks;
pub mod itunes_playlists;
pub mod library;
pub mod library_hashes;
pub mod playlist_tracks;
pub mod playlists;
pub mod rhythmbox_library;
pub mod rhythmbox_playlist_tracks;
pub mod rhythmbox_playlists;
pub mod settings;
pub mod track_analysis;
pub mod track_locations;
pub mod traktor_library;
pub mod traktor_playlist_tracks;
pub mod traktor_playlists;
