//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Playlists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: Option<String>,
    pub position: Option<i32>,
    pub hidden: i32,
    pub date_created: Option<DateTime>,
    pub date_modified: Option<DateTime>,
    pub locked: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::playlist_tracks::Entity")]
    PlaylistTracks,
}

impl Related<super::playlist_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistTracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
