//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "traktor_playlist_tracks")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub playlist_id: Option<i32>,
    pub track_id: Option<i32>,
    pub position: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::traktor_library::Entity",
        from = "Column::TrackId",
        to = "super::traktor_library::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TraktorLibrary,
    #[sea_orm(
        belongs_to = "super::traktor_playlists::Entity",
        from = "Column::PlaylistId",
        to = "super::traktor_playlists::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TraktorPlaylists,
}

impl Related<super::traktor_library::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TraktorLibrary.def()
    }
}

impl Related<super::traktor_playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TraktorPlaylists.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
