//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cues")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub track_id: i32,
    pub r#type: i32,
    pub position: i32,
    pub length: i32,
    pub hotcue: i32,
    pub label: String,
    pub color: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
