//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "itunes_library")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub artist: Option<String>,
    pub title: Option<String>,
    pub album: Option<String>,
    pub year: Option<String>,
    pub genre: Option<String>,
    pub tracknumber: Option<String>,
    pub location: Option<String>,
    pub comment: Option<String>,
    pub duration: Option<i32>,
    pub bitrate: Option<i32>,
    pub bpm: Option<i32>,
    pub rating: Option<i32>,
    pub grouping: Option<String>,
    pub album_artist: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::itunes_playlist_tracks::Entity")]
    ItunesPlaylistTracks,
}

impl Related<super::itunes_playlist_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ItunesPlaylistTracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
