//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "track_analysis")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub track_id: i32,
    pub r#type: Option<String>,
    pub description: Option<String>,
    pub version: Option<String>,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(None))", nullable)]
    pub created: Option<Vec<u8>>,
    pub data_checksum: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::track_locations::Entity",
        from = "Column::TrackId",
        to = "super::track_locations::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TrackLocations,
}

impl Related<super::track_locations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TrackLocations.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
